### ISSUE TITLE
在API12下报错如下

### ISSUE THREAD

**Issue by wangsm123** [tianmuji/Fabric4HarmonyOS#1]
我再HarmonyOS API12下使用fabric，运行时报错，如截图，麻烦看下是为什么
`1 ERROR: ArkTS:ERROR File: D:/svn_work/Harmony_work/WinmageScan/oh_modules/.ohpm/fabric@6.0.0/oh_modules/fabric/src/shapes/IText/ITextClickBehavior.ts:15:45
 Conversion of type 'ClickEvent' to type 'MouseEvent' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.

2 ERROR: ArkTS:ERROR File: D:/svn_work/Harmony_work/WinmageScan/oh_modules/.ohpm/fabric@6.0.0/oh_modules/fabric/src/shapes/IText/ITextClickBehavior.ts:15:45
 Conversion of type 'ClickEvent' to type 'MouseEvent' may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.
  Type 'ClickEvent' is missing the following properties from type 'MouseEvent': button, action, stopPropagation
`

**Comment by tianmuji** [comment]
过节去了

如果着急的话可以自己构建一下
建议使用old分支本地运行

**Comment by tianmuji** [comment]
IText这个类可以删除，本地引入你构建的包试下

或者你项目根目录按转试试呢

如果修改代码再加上鸿蒙那边审核 肯定要到中秋之后才能使用了

**Comment by wangsm123** [comment]
感谢，期待您的更新

**Comment by tianmuji** [comment]
> 感谢，期待您的更新

@wangsm123 你的问题解决了么
你本地构建的包可以运行吧，如果可以的话我关闭这个issue

我这边包在审核中，新包除去了IText类，其他保持不变

**Comment by waj1994** [comment]
@tianmuji   新的包还没审核通过吗？目前下载的还是报这个错误

**Comment by tianmuji** [comment]
@waj1994 @wangsm123 
报错在
const notALeftClick = (e: ClickEvent) => !!(e as MouseEvent).button;

修改成
const notALeftClick = (e: ClickEvent) => !!(e as unkonwn as MouseEvent).button;

可以先本地解决

我密钥丢了 新包一时半会传不上来

**Comment by tianmuji** [comment]
@waj1994 @wangsm123 已上架审核, 可以明天下午尝试更新到v6.0.01
